import { execFileSync } from "node:child_process";
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const scriptDir = dirname(fileURLToPath(import.meta.url));
const packageDir = resolve(scriptDir, "..");
const repoRoot = resolve(packageDir, "..", "..");
const target = "wasm32-unknown-unknown";
const profile = "release";

execFileSync(
  "cargo",
  ["build", "-p", "mcd-wasm", "--target", target, "--release"],
  {
    cwd: repoRoot,
    stdio: "inherit",
  },
);

const wasmPath = resolve(
  repoRoot,
  "target",
  target,
  profile,
  "mcd_wasm.wasm",
);
const wasm = readFileSync(wasmPath).toString("base64");
const generatedPath = resolve(packageDir, "src", "wasm-bytes.ts");

mkdirSync(dirname(generatedPath), { recursive: true });
writeFileSync(
  generatedPath,
  `// Generated by scripts/build-wasm.mjs. Do not edit by hand.\nexport const wasmBase64: string = "${wasm}";\n`,
);
